name: Lovegrove
favicon: null
layout_spectrum: 0.62285
typography_spectrum: 0.49779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e62400'
    - '#080d07'
    - '#93a853'
    - '#636661'
  brandStrength: 0.5
  lightness: 0.9875446786172688
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
